# .sops.yaml
#
# Add servers with:
#   ssh-keyscan -t ed25519 hostname | nix run nixpkgs#ssh-to-age.
#
# Edit secrets with:
#   nix run nixpkgs#sops -- hosts/name/secrets/secrets.yml
#
# Use sops updatekeys command to re-key corresponding files:
#   nix run nixpkgs#sops -- updatekeys file.
#

# Public keys
keys:
  - &hosts:
      - &atlas age1gef7ypvn8lzjppymnnj0lxyq60jsmcnagqayfevjpu9qx64ll9rqv6hzf9
      # - &kronos
# Creation rules referencing the upon public keys
creation_rules:
  - path_regex: home/valentino/modules/credentials/ssh/*
    key_groups:
    - age:
        - *atlas
  # - path_regex: secrets/secrets.yaml
  #   key_groups:
  #   - age:
  #       - *atlas
